Java fx to swing
Project2GLvideoGame/Game pull request #24
Opened 2022-11-13 15:06 UTC by damiengazaix

2022-11-13 16:56 UTC, LPMusardo requested changes

2022-11-13 16:56 UTC, LPMusardo commented on app/src/main/java/game/App.java
> -    public static void main(String[] args) {
Tout ce qui est en rapport avec window et Swing ca serait bien de le sortir du main, et de la mettre dans graphicEngine

2022-11-13 16:56 UTC, LPMusardo commented on app/src/main/java/game/Kernel.java
> +    public void run(){
Toute la gestion du temps elle est propre au GraphicEngine est ce qu'il y a pas moyen que ca se fasse dans la classe GraphicEngine du coup ?

2022-11-13 16:56 UTC, LPMusardo commented on app/src/main/java/game/Graphic/GraphicEngine.java
> +public class GraphicEngine extends JPanel{
Est ce que GraphicEngine ne devrait pas créer son JPanel en interne plutôt que de l'extend ?

2022-11-13 20:50 UTC, LPMusardo approved these changes

2022-11-14 13:50 UTC, MaximeGuiliani approved these changes

2022-11-14 14:03 UTC, merged